### PR TITLE
Remove useless copy message

### PR DESCRIPTION
**Pull request by MikaelMayer**
Added a check so that if the files are up to date, they are not copied and no message is displayed.

### CODE REVIEW

**Comment by larsrh** [comment]
Thanks for your initiative? Did you try this out locally, e.g. on Leon? Because if I add your patch it still prints the message on every `package`.

**Comment by MikaelMayer** [comment]
No I did not try, how can I on my machine? I'm very new to sbt plugins.

2016-06-28 17:53 GMT+02:00 Lars Hupel <notifications@github.com>:

**Comment by larsrh** [comment]
It's slightly inconvenient but not difficult.
1. In Leon, change the version of the `sbt-libisabelle` plugin to `0.2-SNAPSHOT`.
2. In the SBT plugin, run `sbt publishLocal`.
3. In Leon, restart SBT and run `package` to see the effects of the changes.
Repeat 2 and 3.

**Comment by MikaelMayer** [comment]
Thanks ! I was able to fix the plug-in using what you say.
Now if it copies files, it will even give the reason why.
This PR is mergeable now.

**Comment by larsrh** [comment]
Thanks much! I'll merge when I'm back from IJCAR.

**Comment by larsrh** [comment]
Merged.

**Pull request merged**
